---
- name: Ensure tmp directory is present
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Ensure dependencies are installed
  become: true
  pacman:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - make
    - git
    - awk
  when: ansible_os_family == "Archlinux"

- name: RCM download package
  get_url:
    url: "{{ rcm_url }}"
    dest: "{{ temp_dir }}"
  register: download

- name: RCM extract package
  unarchive:
    remote_src: true
    src: "{{ download.dest }}"
    dest: "{{ temp_dir }}"
    list_files: true
  register: extract

- name: RCM install
  become: yes
  shell: cd "{{ extract.files[0] }}" && ./configure && make && make install
  args:
    chdir: "{{ temp_dir }}"

- name: Check if dotfiles directory is present
  stat:
    path: "{{ ansible_env.HOME }}/.public-dotfiles"
  register: stat_result

- name: Clone dotfiles from repo
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ ansible_env.HOME }}/.public-dotfiles"
  when: not stat_result.stat.exists

- name: Pull dotfiles from repo
  shell: git pull
  args:
    chdir: "{{ ansible_env.HOME }}/.public-dotfiles"
  when: stat_result.stat.exists

- name: Link dotfiles and exclude meta files
  command: rcup -d .public-dotfiles -f '{% for arg1 in excluded_files %}-x {{arg1 }}{% if not loop.last %}{% endif %} {% endfor %}'  #-x README -x LICENSE -x screenshot.png
  args:
    chdir: "{{ ansible_env.HOME }}"

- name: Create global gitconfig
  template:
    src: templates/gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    force: true
